import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export interface CountryCurrency {
  name: string
  code: string
  currencyName: string
  currencySymbol: string
  flag: string
}

const getFlagUrl = (fileName: string) =>
  new URL(`../assets/images/flags/${fileName}`, import.meta.url).href

export function getCountries(): CountryCurrency[] {
  return [
    {
      name: "United Arab Emirates",
      code: "AE",
      currencyName: "United Arab Emirates Dirham",
      currencySymbol: "\u062f.\u0625",
      flag: getFlagUrl("ae.webp"),
    },
    {
      name: "Argentina",
      code: "AR",
      currencyName: "Argentine Peso",
      currencySymbol: "$",
      flag: getFlagUrl("ar.webp"),
    },
    {
      name: "Australia",
      code: "AU",
      currencyName: "Australian Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("au.webp"),
    },
    {
      name: "Bangladesh",
      code: "BD",
      currencyName: "Bangladeshi Taka",
      currencySymbol: "\u09f3",
      flag: getFlagUrl("bd.webp"),
    },
    {
      name: "Bulgaria",
      code: "BG",
      currencyName: "Bulgarian Lev",
      currencySymbol: "\u043b\u0432",
      flag: getFlagUrl("bg.webp"),
    },
    {
      name: "Bahrain",
      code: "BH",
      currencyName: "Bahraini Dinar",
      currencySymbol: ".\u062f.\u0628",
      flag: getFlagUrl("bh.webp"),
    },
    {
      name: "Brazil",
      code: "BR",
      currencyName: "Brazilian Real",
      currencySymbol: "R$",
      flag: getFlagUrl("br.webp"),
    },
    {
      name: "Canada",
      code: "CA",
      currencyName: "Canadian Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("ca.webp"),
    },
    {
      name: "Switzerland",
      code: "CH",
      currencyName: "Swiss Franc",
      currencySymbol: "CHF",
      flag: getFlagUrl("ch.webp"),
    },
    {
      name: "Chile",
      code: "CL",
      currencyName: "Chilean Peso",
      currencySymbol: "$",
      flag: getFlagUrl("cl.webp"),
    },
    {
      name: "China",
      code: "CN",
      currencyName: "Chinese Yuan",
      currencySymbol: "\u00a5",
      flag: getFlagUrl("cn.webp"),
    },
    {
      name: "Colombia",
      code: "CO",
      currencyName: "Colombian Peso",
      currencySymbol: "$",
      flag: getFlagUrl("co.webp"),
    },
    {
      name: "Cyprus",
      code: "CY",
      currencyName: "Euro",
      currencySymbol: "\u20ac",
      flag: getFlagUrl("cy.webp"),
    },
    {
      name: "Czech Republic",
      code: "CZ",
      currencyName: "Czech Koruna",
      currencySymbol: "K\u010d",
      flag: getFlagUrl("cz.webp"),
    },
    {
      name: "Denmark",
      code: "DK",
      currencyName: "Danish Krone",
      currencySymbol: "kr",
      flag: getFlagUrl("dk.webp"),
    },
    {
      name: "Egypt",
      code: "EG",
      currencyName: "Egyptian Pound",
      currencySymbol: "\u00a3",
      flag: getFlagUrl("eg.webp"),
    },
    {
      name: "European Union",
      code: "EU",
      currencyName: "Euro",
      currencySymbol: "\u20ac",
      flag: getFlagUrl("eu.webp"),
    },
    {
      name: "United Kingdom",
      code: "GB",
      currencyName: "British Pound",
      currencySymbol: "\u00a3",
      flag: getFlagUrl("gb.webp"),
    },
    {
      name: "Hong Kong",
      code: "HK",
      currencyName: "Hong Kong Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("hk.webp"),
    },
    {
      name: "Heard Island and McDonald Islands",
      code: "HM",
      currencyName: "Australian Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("hm.webp"),
    },
    {
      name: "Honduras",
      code: "HN",
      currencyName: "Honduran Lempira",
      currencySymbol: "L",
      flag: getFlagUrl("hn.webp"),
    },
    {
      name: "Croatia",
      code: "HR",
      currencyName: "Euro",
      currencySymbol: "\u20ac",
      flag: getFlagUrl("hr.webp"),
    },
    {
      name: "Haiti",
      code: "HT",
      currencyName: "Haitian Gourde",
      currencySymbol: "G",
      flag: getFlagUrl("ht.webp"),
    },
    {
      name: "Hungary",
      code: "HU",
      currencyName: "Hungarian Forint",
      currencySymbol: "Ft",
      flag: getFlagUrl("hu.webp"),
    },
    {
      name: "Indonesia",
      code: "ID",
      currencyName: "Indonesian Rupiah",
      currencySymbol: "Rp",
      flag: getFlagUrl("id.webp"),
    },
    {
      name: "India",
      code: "IN",
      currencyName: "Indian Rupee",
      currencySymbol: "\u20b9",
      flag: getFlagUrl("in.webp"),
    },
    {
      name: "Iceland",
      code: "IS",
      currencyName: "Icelandic Krona",
      currencySymbol: "kr",
      flag: getFlagUrl("is.webp"),
    },
    {
      name: "Jordan",
      code: "JO",
      currencyName: "Jordanian Dinar",
      currencySymbol: "\u062f.\u0627",
      flag: getFlagUrl("jo.webp"),
    },
    {
      name: "Japan",
      code: "JP",
      currencyName: "Japanese Yen",
      currencySymbol: "\u00a5",
      flag: getFlagUrl("jp.webp"),
    },
    {
      name: "Kenya",
      code: "KE",
      currencyName: "Kenyan Shilling",
      currencySymbol: "KSh",
      flag: getFlagUrl("ke.webp"),
    },
    {
      name: "South Korea",
      code: "KR",
      currencyName: "South Korean Won",
      currencySymbol: "\u20a9",
      flag: getFlagUrl("kr.webp"),
    },
    {
      name: "Kuwait",
      code: "KW",
      currencyName: "Kuwaiti Dinar",
      currencySymbol: "\u062f.\u0643",
      flag: getFlagUrl("kw.webp"),
    },
    {
      name: "Lebanon",
      code: "LB",
      currencyName: "Lebanese Pound",
      currencySymbol: "\u0644.\u0644",
      flag: getFlagUrl("lb.webp"),
    },
    {
      name: "Saint Lucia",
      code: "LC",
      currencyName: "Eastern Caribbean Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("lc.webp"),
    },
    {
      name: "Sri Lanka",
      code: "LK",
      currencyName: "Sri Lankan Rupee",
      currencySymbol: "Rs",
      flag: getFlagUrl("lk.webp"),
    },
    {
      name: "Morocco",
      code: "MA",
      currencyName: "Moroccan Dirham",
      currencySymbol: "\u062f.\u0645.",
      flag: getFlagUrl("ma.webp"),
    },
    {
      name: "Mexico",
      code: "MX",
      currencyName: "Mexican Peso",
      currencySymbol: "$",
      flag: getFlagUrl("mx.webp"),
    },
    {
      name: "Malaysia",
      code: "MY",
      currencyName: "Malaysian Ringgit",
      currencySymbol: "RM",
      flag: getFlagUrl("my.webp"),
    },
    {
      name: "Nigeria",
      code: "NG",
      currencyName: "Nigerian Naira",
      currencySymbol: "\u20a6",
      flag: getFlagUrl("ng.webp"),
    },
    {
      name: "Norway",
      code: "NO",
      currencyName: "Norwegian Krone",
      currencySymbol: "kr",
      flag: getFlagUrl("no.webp"),
    },
    {
      name: "Nepal",
      code: "NP",
      currencyName: "Nepalese Rupee",
      currencySymbol: "\u20a8",
      flag: getFlagUrl("np.webp"),
    },
    {
      name: "New Zealand",
      code: "NZ",
      currencyName: "New Zealand Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("nz.webp"),
    },
    {
      name: "Oman",
      code: "OM",
      currencyName: "Omani Rial",
      currencySymbol: "\u0631.\u0639.",
      flag: getFlagUrl("om.webp"),
    },
    {
      name: "Peru",
      code: "PE",
      currencyName: "Peruvian Sol",
      currencySymbol: "S/",
      flag: getFlagUrl("pe.webp"),
    },
    {
      name: "Philippines",
      code: "PH",
      currencyName: "Philippine Peso",
      currencySymbol: "\u20b1",
      flag: getFlagUrl("ph.webp"),
    },
    {
      name: "Pakistan",
      code: "PK",
      currencyName: "Pakistani Rupee",
      currencySymbol: "Rs",
      flag: getFlagUrl("pk.webp"),
    },
    {
      name: "Poland",
      code: "PL",
      currencyName: "Polish Zloty",
      currencySymbol: "z\u0142",
      flag: getFlagUrl("pl.webp"),
    },
    {
      name: "Qatar",
      code: "QA",
      currencyName: "Qatari Riyal",
      currencySymbol: "\u0631.\u0642",
      flag: getFlagUrl("qa.webp"),
    },
    {
      name: "Romania",
      code: "RO",
      currencyName: "Romanian Leu",
      currencySymbol: "lei",
      flag: getFlagUrl("ro.webp"),
    },
    {
      name: "Russia",
      code: "RU",
      currencyName: "Russian Ruble",
      currencySymbol: "\u20bd",
      flag: getFlagUrl("ru.webp"),
    },
    {
      name: "Saudi Arabia",
      code: "SA",
      currencyName: "Saudi Riyal",
      currencySymbol: "\ufdfc",
      flag: getFlagUrl("sa.webp"),
    },
    {
      name: "Sweden",
      code: "SE",
      currencyName: "Swedish Krona",
      currencySymbol: "kr",
      flag: getFlagUrl("se.webp"),
    },
    {
      name: "Singapore",
      code: "SG",
      currencyName: "Singapore Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("sg.webp"),
    },
    {
      name: "Thailand",
      code: "TH",
      currencyName: "Thai Baht",
      currencySymbol: "\u0e3f",
      flag: getFlagUrl("th.webp"),
    },
    {
      name: "Turkey",
      code: "TR",
      currencyName: "Turkish Lira",
      currencySymbol: "\u20ba",
      flag: getFlagUrl("tr.webp"),
    },
    {
      name: "Taiwan",
      code: "TW",
      currencyName: "New Taiwan Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("tw.webp"),
    },
    {
      name: "Ukraine",
      code: "UA",
      currencyName: "Ukrainian Hryvnia",
      currencySymbol: "\u20b4",
      flag: getFlagUrl("ua.webp"),
    },
    {
      name: "United States",
      code: "US",
      currencyName: "United States Dollar",
      currencySymbol: "$",
      flag: getFlagUrl("us.webp"),
    },
    {
      name: "Vietnam",
      code: "VN",
      currencyName: "Vietnamese Dong",
      currencySymbol: "\u20ab",
      flag: getFlagUrl("vn.webp"),
    },
    {
      name: "South Africa",
      code: "ZA",
      currencyName: "South African Rand",
      currencySymbol: "R",
      flag: getFlagUrl("za.webp"),
    },
  ]
}
